variable "rgname" {}
variable "rgloc" {}
variable "v_net" {}
variable "add_space" {}
variable "subnetname" {}
variable "add_pref" {}
variable "publicip_name" {}
variable "alloc_method" {}
variable "nic_name" {}
variable "nic_ip_conf_name" {}
variable "private_ip_add_alloc" {}
variable "nsg_sec_name" {}
variable "nsg_nameforvm" {}
variable "nsg_prority" {}
variable "nsg_dir" {}
variable "nsg_access" {}
variable "nsg_protocol" {}
variable "nsg_sour_port_range" {}
variable "nsg_des_port_range" {}
variable "nsg_sour_add_pref" {}
variable "nsg_des_add_pref" {}
variable "win_VM" {}
variable "win_VM_size" {}
variable "win_VM_username" {}
variable "win_VM_pwd" {}
variable "os_disk" {}
variable "strg_acc_type" {}
variable "sipublisher" {}
variable "sioffer" {}
variable "sisku" {}
variable "siversion" {}